[project]
name = "oleo-phase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "polars>=1.30.0",
    "scipy>=1.15.3",
]
